### ISSUE TITLE
about the efficiency 

### ISSUE THREAD

**Issue by yfpeng1234** [tyui592/pytorch_FlexMatch#1]
Hi, thanks for providing this implementation!
But when I was running the code, I found it's a little bit slow.
I use the same default arguments as you do, dataset is cifar10, but it cost almost 7~10 minutes to complete a train step(1024 iteration), I also try to use small model like tiny convnet, but it was still very slow.
I don't know how to figure out the bottleneck of the efficiency.

**Comment by yfpeng1234** [comment]
Actually I use a Nvidia A6000 to run it

**Comment by tyui592** [comment]
Hello, thanks for the report.
I also took 7 minutes for one step as you can see in the log file of the [release note](https://github.com/tyui592/pytorch_FlexMatch/releases). (Check: 015.zip/log015.out)
I think the implementation has more space to improve efficiency, but I don't have plan for it now.
So if you need faster implementation, please check [TorchSSL](https://github.com/TorchSSL/TorchSSL?tab=readme-ov-file). (it takes approximately 6 minutes per 1024 iterations.)
